# Generated by Django 3.0.3 on 2020-03-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dento',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='post',
            name='kuchou',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='post',
            name='nengetu',
            field=models.CharField(default=202001, max_length=6),
        ),
    ]
