# Generated by Django 3.0.4 on 2020-03-18 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200310_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dento',
            field=models.IntegerField(default=0, verbose_name='電灯使用量'),
        ),
        migrations.AlterField(
            model_name='post',
            name='kuchou',
            field=models.IntegerField(default=0, verbose_name='空調使用量'),
        ),
        migrations.AlterField(
            model_name='post',
            name='nengetu',
            field=models.CharField(default=202001, max_length=6, verbose_name='年月'),
        ),
    ]
